Master:
  Name: jenkins-master
  Image: "jenkins/jenkins"
  ImageTag: "2.277.3-jdk11"
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: admin
  Cpu: "200m"
  Memory: "1Gi"
  ServicePort: 8080
  ServiceType: NodePort
  NodePort: 32000
  ServiceAnnotations: {}
  ContainerPort: 8080
  HealthProbes: true
  HealthProbesTimeout: 60
  SlaveListenerPort: 50000
  LoadBalancerSourceRanges:
    - 0.0.0.0/0
  InstallPlugins:
    - kubernetes:latest
    - workflow-aggregator:2.5
    - workflow-job:2.31
    - credentials-binding:1.17
    - git:3.9.3
    - git-client:2.7.6
    - greenballs:latest
    - ws-cleanup:0.37
  ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
  CustomConfigMap: false
  NodeSelector: {}
  Tolerations: {}

Agent:
  Enabled: true
  Image: "jenkins/inbound-agent"
  ImageTag: "4.6-1"
  Component: "jenkins-slave"
  Privileged: false
  Cpu: "200m"
  Memory: "512Mi"
  # You may want to change this to true while testing a new image
  AlwaysPullImage: false
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
  NodeSelector: {}

Persistence:
  Enabled: true
  StorageClass: jenkins-pv

  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 2Gi
  volumes:
  #  - name: nothing
  #    emptyDir: {}
  mounts:
  #  - mountPath: /var/nothing
  #    name: nothing
  #    readOnly: true

NetworkPolicy:
  Enabled: false
  ApiVersion: networking.k8s.io/v1

rbac:
  install: true
  serviceAccountName: default
  apiVersion: v1beta1
  roleRef: cluster-admin
