    pipeline {
        agent any
        
        tools {nodejs "Node-build"}
    stages {
        
    stage('Prepare environment') {
        steps {

    git branch: 'application', url: 'https://github.com/vanek-k/dip.git'
   
 
}
    }



    stage('Code analyse') {
        steps {

    sh 'echo “Run some lints”'

    }
    }
    stage ('Unit test') {
        steps {

    sh 'echo “Tests will back”'

    }
    }
    stage ('Build') {
       steps {
                sh 'npm install'

    sh 'npm run build'
   
    
    sh 'npm config ls'
    
    sh 'ls -a'
    //sh 'npm run clean'
   // sh 'npm run build'

                
            }
        }
    }
}
